version: "3.5"
services:
  app:
    build: .
    command: python pars/parser.py
    volumes:
      - ./pars/:/app/pars/
    ports:
      - "80:80"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shorter
    ports:
      - "5435:5435"


